---
- name: reload systemd configuration
  ansible.builtin.command: systemctl daemon-reload

- name: restart kafka deamon
  ansible.builtin.service:
    name: kafka
    state: restarted
    enabled: true
    
- name: restart zookeeper deamon
  ansible.builtin.service:
    name: zookeeper
    state: restarted
    enabled: true
