---
- name: restart kafka deamon
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    daemon_reload: true

- name: restart zookeeper deamon
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
    daemon_reload: true
