---
- name: create kafka group
  ansible.builtin.group:
    name: '{{ kafka_group }}'
    state: present
    system: yes

- name: create kafka user
  ansible.builtin.user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    system: yes

- name: create kafka data log dir
  file:
    path: '/home/{{ kafka_user }}/data/kafka'
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755

- name: create kafka application log dir
  file:
    path: '/home/{{ kafka_user }}/logs/kafka'
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755

- name: create zookeeper log dir
  file:
    path: /home/{{ kafka_user }}/data/zookeeper
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755
