---
- name: init
  include: init.yaml

- name: install java
  include: java.yaml

- name: ensure kafka
  block:
    - name: ensure kafka downalod directory
      ansible.builtin.file:
        path: /home/kafka/downloads
        state: directory
        mode: 0755

    - name: download kafka
      ansible.builtin.get_url:
        url: 'https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz'
        dest: /home/kafka/downloads
      
    - name: unarchive kafka archive
      ansible.builtin.unarchive:
        src: '/home/kafka/downloads/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz'
        dest: '/home/kafka'
        remote_src: true
    - name: create symlink
      ansible.builtin.file:
        src: '/home/kafka/kafka_{{ kafka_scala_version }}-{{ kafka_version }}'
        dest: /home/kafka/kafka
        state: link
        group: '{{ kafka_group }}'
        owner: '{{ kafka_user }}'

- name: template jaas config
  block:
    - name: create jaas config directory
      ansible.builtin.file:
        path: '/home/kafka/kafka/config/jaas'
        state: directory
        group: '{{ kafka_group }}'
        owner: '{{ kafka_user }}'
        mode: 0755
    - name: template kafka jaas config
      ansible.builtin.template:
        src: kafka_server_jaas.conf.j2
        dest: /home/kafka/kafka/config/jaas/kafka_server_jaas.conf
        group: '{{ kafka_group }}'
        owner: '{{ kafka_user }}'
        mode: 0644
    - name: template zookeeper jaas config
      ansible.builtin.template:
        src: zookeeper_jaas.conf.j2
        dest: /home/kafka/kafka/config/jaas/zookeeper_jaas.conf
        group: '{{ kafka_group }}'
        owner: '{{ kafka_user }}'
        mode: 0644
  
- name: template config
  block:
  - name: template zookeeper config
    ansible.builtin.template:
      src: zookeeper.properties.j2
      dest: '/home/kafka/kafka/config/zookeeper.properties'
      group: '{{ kafka_group }}'
      owner: '{{ kafka_user }}'
      mode: 0644
    notify:
      - reload systemd configuration
      - restart zookeeper deamon

  - name: template kafka config
    ansible.builtin.template:
      src: server.properties.j2
      dest: '/home/kafka/kafka/config/server.properties'
      group: '{{ kafka_group }}'
      owner: '{{ kafka_user }}'
      mode: 0644
    notify:
      - reload systemd configuration
      - restart kafka deamon

- name: template service
  block:
  - name: template zookeeper.service
    ansible.builtin.template:
      src: zookeeper.service.j2
      dest: /usr/lib/systemd/system/zookeeper.service
      group: '{{ kafka_group }}'
      owner: '{{ kafka_user }}'
      mode: 0644
    notify:
      - reload systemd configuration
      - restart zookeeper deamon
    
  - name: template kafka.service
    ansible.builtin.template:
      src: kafka.service.j2
      dest: /usr/lib/systemd/system/kafka.service
      group: '{{ kafka_group }}'
      owner: '{{ kafka_user }}'
      mode: 0644
    notify:
      - reload systemd configuration
      - restart kafka deamon

# https://knight76.tistory.com/entry/kafka-kafkacommonInconsistentBrokerIdException-Configured-brokerid-2-doesnt-match-stored-brokerid-0-in-metaproperties-%ED%95%B4%EA%B2%B0-%ED%95%98%EA%B8%B0
- name: delete meta properties if it exists
  file:
    path: /home/kafka/logs/kafka/meta.properties
    state: absent
    
- name: start daemon
  block:
  - name: start zookeeper daemon
    ansible.builtin.service:
      name: zookeeper
      state: started
      enabled: true

  - name: start kafka daemon
    ansible.builtin.service:
      name: kafka
      state: started
      enabled: true
